vich_uploader:
    db_driver: orm

    mappings:
        file_upload:
            uri_prefix: /cours/files
            upload_destination: '%kernel.project_dir%/public/cours/files'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
